name: Build and deploy .NET Core web application to Azure App Service
on:
  workflow_dispatch:
  #push:
    #branches:
    #- master
jobs:
  build-and-deploy:
    runs-on: windows-latest # For Linux, use ubuntu-latest
    environment: dev
    steps:
    
    - name: Sign in to Azure 
    # Use the GitHub secret you added.
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
    - name: Deploy to Azure Web App
    # Remove publish-profile.
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'sampleApp-gldemo'
        slot-name: 'dev'
        package: .
      
    - name: Sign out of Azure.
      run: |
        az logout
